- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
- apim-operator/pkg/controller/ratelimiting/ratelimiting_controller.go
Default policies.yaml is created for the first time in ratelimiting controller and new policies are appended to it. But if user does not deploy any ratelimiting crd objects, this code handles it by creating a default policy configmap in the api controller.
> Handling default ratelimiting policies

- apim-operator/deploy/kubectl-extension/kubectl-add
- apim-operator/pkg/controller/api/api_controller.go
> Earlier we added modifications which are required for mgw to the original swagger directly. So need to keep original one as it is in a configmap and edited swagger will keep in separate configmap. 
> Resource level endpoints should be replaced with localhost when the deployment is defined as sidecar.  
> Brief description of the new feature or bug fix as it will appear …
> Adding support to keep both original and edited swaggers in configmaps & Handling resource level endpoints with sidecar deployment 

- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/ratelimiting/ratelimiting_controller.go
Fix #186 
When the apim-operator is deployed in a namespace other than wso2-system, the controllers run in an error loop forever when a custom resource is deployed.
This PR fixes it.
> Fix the controller looping when the operator is not in wso2-system namespace

- k8s-artifacts/api-portal-with-analytics/api-analytics/analytics-dashboard-deployment.yaml
Fixes #185 
When the API portal pod or mysql services are not available, the analytics dashboard is not accessible although the analytics dashboard pod status is displayed as 'Ready'.
To make it easier for the user to debug,this PR keeps the analytics dashboard in init state when the api portal or mysql is not available. When the api portal and mysql services are available the dashboard is put to ready state.
> Improve analytics dashboard deployment in k8s

- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/utils.go
fix #234 
Copy registry specific secrets and configmaps (configured while installing the operator) from wso2-system to user's namespace.
> Copy secrets and configmaps from wso2-system to user's namespace

- apim-operator/deploy/controller-configs/docker_registry_conf.yaml
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
- toolkit-docker-image/Dockerfile
fix #253 
- Fix overriding err value when getting ingress conf
- Move docker registry data to 'docker-registry-config' configmap
- Change toolkit dockerfile base image
- Related apictl changes: https://github.com/wso2/product-apim-tooling/pull/229
> Move docker registry data to 'docker-registry-config' configmap

- apim-operator/pkg/registry/amazon_ecr.go
- apim-operator/pkg/registry/dockerhub.go
- apim-operator/pkg/registry/gcr.go
- apim-operator/pkg/registry/utils/consts.go
fix wso2/K8s-api-operator#258
- Rename registry specific secrets and configmaps
- Related APICTL changes: https://github.com/wso2/product-apim-tooling/pull/230
> Rename registry specific secrets and configmaps

- api-operator/pkg/registry/amazon_ecr.go
- fix #283 - Check this for more info
- Check for untagged ECR image to avoid nil pointer panic in the api-operator.
In any case if there is a untagged image in the repository current setup of the api-operator leads to a nil pointer panic.
Check for the pointer `id.ImageTag` nil and otherwise read the the pointer value `*id.ImageTag`
> Check for untagged ECR image to avoid nil pointer panic

- api-operator/deploy/controller-configs/mgw_conf_mustache.yaml
Fix JWT token config indentation
fix wso2/k8s-api-operator#366
> Fix JWT token config indentation

- docs/HowToGuide/OverviewOfCrds/apply-rate-limiting-to-api.md
- docs/HowToGuide/OverviewOfCrds/apply-security-to-api.md
- docs/HowToGuide/configurations-overview.md
This PR includes the following changes to how to guide docs:
- how to configure the default security modifications
- update the apply rate limiting and security docs with related to defining the namespace
> Update configs and CRDs in how to guide docs

- toolkit-docker-image/Dockerfile
- toolkit-docker-image/ReadMe.md
- Update MGW toolkit image version
- Update toolkit ReadMe.md file (preview: https://github.com/renuka-fernando/k8s-api-operator/blob/mgw-toolkit-320-alpha/toolkit-docker-image/ReadMe.md)
- Pushed the image `wso2am/wso2micro-gw-toolkit:3.2.0-alpha`
> Update MGW toolkit image version and ReadMe.md file

- api-operator/deploy/controller-configs/controller_conf.yaml
- api-operator/deploy/controller-configs/mgw_conf_mustache.yaml
- api-operator/deploy/crds/wso2_v1alpha1_security_crd.yaml
- api-operator/pkg/apis/wso2/v1alpha1/security_types.go
- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/controller/security/security_controller.go
- api-operator/pkg/mgw/config.go
- api-operator/pkg/security/const.go
- api-operator/pkg/security/security.go
- scenarios/scenario-19/README.md
- scenarios/scenario-19/apiKey-security.yaml
- scenarios/scenario-19/swagger.yaml
> Adding API Key support for K8S operator
> 
- Introduced Configurations related to API key issuer in the controller_conf.yaml under apim-config.
- API key validation related configurations need to be included in the security custom resource.
- Security CR created should be referred in the Swagger definition using security extension.
> When an user needs to deploy a service on a kubernetes cluster as a managed API secured with API key authentication. 
> 
- go version go1.14.2 linux/amd64
- Ubuntu 18.04.4 LTS
> Adding API Key feature

- api-operator/pkg/k8s/mount.go
This shortens the mount suffix to `-vol`.
Relevant issue - https://github.com/wso2/k8s-api-operator/issues/345
> Limiting configmap names

- README.md
- api-operator/README.md
- api-operator/deploy/controller-artifacts/operator.yaml
- distribution/pom.xml
- docs/GettingStarted/overview.md
- docs/GettingStarted/quick-start-guide.md
- docs/HowToGuide/OverviewOfCrds/apply-rate-limiting-to-api.md
- docs/HowToGuide/OverviewOfCrds/perform-api-operations.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-aws.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-gcr.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-http-https-repository.md
- docs/HowToGuide/install-api-operator-in-cicd.md
- docs/HowToGuide/working-with-kaniko-additional-flags.md
- k8s-artifacts/api-portal-with-analytics/api-analytics/analytics-dashboard-deployment.yaml
- k8s-artifacts/api-portal-with-analytics/api-analytics/analytics-worker-deployment.yaml
- k8s-artifacts/api-portal-with-analytics/api-portal/wso2apim-deployment.yaml
- k8s-artifacts/api-portal/wso2apim-deployment.yaml
- pom.xml
- scenarios/scenario-1/README.md
- scenarios/scenario-11/README.md
- scenarios/scenario-13/S01-APIM_for_Istio_Services/README.md
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/README.md
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/README.md
- Update WSO2AM, Analytics docker images and operator image
- Update build from source doc
- Change the version as "1.2.0-alpha
- Update documents with new apictl install api-operator command output
- Remove docker.io prefix for repository name of Docker Hub from docs
- Brake lines for long sentences
> Update docs for 1.2.0 alpha release

- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/controller/api/constants.go
- api-operator/pkg/interceptors/interceptors.go
- api-operator/pkg/kaniko/docker.go
- api-operator/pkg/mgw/api.go
- api-operator/pkg/mgw/ingress.go
- api-operator/pkg/mgw/route.go
This PR,
1. Improves the information returned by `kubectl describe apis` command by adding events related to the specific API resource. This is done by introducing an event recorder to the api-controller which will send custom events to the relevant resource.
Related issue - https://github.com/wso2/k8s-api-operator/issues/334
However, the events will be removed after 1 hour by the garbage collector in Kubernetes.
```
$ kubectl describe apis petstore-api
Events:
Type    Reason            Age                From            Message
----    ------            ----               ----            -------
Normal  Configs           15m (x3 over 18m)  api-controller  Creating swagger configmap for MGW.
Normal  Configs           15m (x3 over 18m)  api-controller  Handling analytics & interceptors, …
```
> Improving information related to APIs by adding events

- api-operator/deploy/controller-configs/default_security_cr.yaml
- api-operator/deploy/controller-configs/mgw_conf_mustache.yaml
- api-operator/pkg/controller/security/security_controller.go
- api-operator/pkg/mgw/config.go
- api-operator/pkg/security/security.go
- scenarios/scenario-4/README.md
- scenarios/scenario-4/jwt-security.yaml
- scenarios/scenario-4/multiple-jwt-security.yaml
- This fixes  #398
- Make the Audience field optional in JWT
- Make the audience field which is in Security Custom Resource (CR) related to JWT optional.
- When an user needs to add audience value he/she can add it in the Security Custom Resource (CR) under security config with audience field.
- JWTs that are taken from the API Manager has an audience that keep changing based on the provider. So it is required to make the audience field optional.
> Make Audience optional field in JWT

- api-operator/pkg/mgw/api.go
- api-operator/pkg/mgw/service.go
fix wso2/k8s-api-operator#388
- Add ingress hostname if IP not found.
```sh
$ kubectl get api
NAME           INITIAL-REPLICAS   MODE         ENDPOINT    AGE
petstore-api   1                  privateJet   localhost   2m46s
```
> Set API endpoint and refactor getting external IP

- api-operator/deploy/controller-configs/controller_conf.yaml
- api-operator/pkg/controller/targetendpoint/constants.go
- api-operator/pkg/controller/targetendpoint/targetendpoint_controller.go
- api-operator/pkg/mgw/config.go
- api-operator/pkg/mgw/hpa.go
- scenarios/scenario-20/README.md
- This fixes some issues related to backend JWT Generation.
- Updates the metrics configurations for hpa versipn "v2beta1".
- When using custom metrics update the scenario-20 docs with regard to changing hpa version to "v2beta2"
> Update metrics configs for hpa version v2beta1

- api-operator/deploy/controller-configs/controller_conf.yaml
- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/k8s/mount.go
- api-operator/pkg/mgw/deployment.go
- api-operator/pkg/mgw/uservolumes.go
- scenarios/scenario-23/README.md
- scenarios/scenario-23/mgw-deploy-configs.yaml
- scenarios/scenario-23/swagger.yaml
- scenarios/scenario-23/test1cm.yaml
- scenarios/scenario-23/test1secret.yaml
- scenarios/scenario-23/test2cm.yaml
- Add support to mount config maps and secrets to micro-gateway deployment.
> Approach 01
- User can add **mgw-deployment-configs** to controller_conf.yaml and provide the config maps and secrets to be added to micro-gateway deployment.
- The config maps and secrets to be added need to be in the same namespace which the **mgw-deployment-configs** is being deployed.
> Approach 02
- User can create and deploy a **mgw-deployment-configs** config map in the same namespace which the API is being deployed and in there he/she can provide the config maps and secrets to be added to micro-gateway deployment.
- The config maps and secrets to be added need to be in the same namespace which the **mgw-deployment-configs**  is being deployed.
> Add support to mount config maps and secrets to mgw deployment

- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/security/default.go
- This fixes #426
- When the user provides multiple jwt issuers in the default security Custom Resource (CR) it will be applied to the micro-gateway conf.
> Apply multiple jwt issuer configs in default security to mgw conf

- api-operator/deploy/controller-artifacts/operator.yaml
- api-operator/pkg/controller/api/api_controller.go
Add components.extensions when it is not defined in swagger definition
fix wso2/k8s-api-operator#444
> Add components.extensions when it is not defined in swagger definition

- api-operator/deploy/controller-artifacts/operator.yaml
- api-operator/pkg/registry/http.go
- api-operator/pkg/registry/https.go
- api-operator/pkg/registry/utils/utils.go
- Fix issue in checking image existence in GCR, DockerHub, ECR
- A fix has done for HTTP/HTTPS private registry has applied for all other registries, so done this only for HTTP/HTTPS registries.
- Move `getImageWithoutReg` to HTTP/HTTPS private registries.
> Fix issue in checking image existence in GCR, Docker Hub, ECR

- api-operator/pkg/kaniko/job.go
fix wso2/k8s-api-operator#451
Add image pull secret for pulling Kaniko image
- Created a docker registry with auth configs (`192.168.8.132:5000`).
- Images
- `192.168.8.132:5000/wso2am/wso2micro-gw-toolkit:3.2.0-rc2`
- `192.168.8.132:5000/wso2/wso2micro-gw:3.2.0-rc2`
- `192.168.8.132:5000/gcr.io/kaniko-project/executor:v0.24.0`
- Push images to the registry
- Docker rmi images (removed above images)
- Install API Operator with following config
```
data:
#mgw toolkit image to initialize/setup the micro gw project
mgwToolkitImg: 192.168.8.132:5000/wso2am/wso2micro-gw-toolkit:3.2.0-rc2
#mgw runtime image to use in the mgw executable
mgwRuntimeImg: 192.168.8.132:5000/wso2/wso2micro-gw:3.2.0-rc2
#kaniko image for the kaniko pod which builds the mgw api runtime and pushes to the registry …
```
> Add image pull secret for pulling Kaniko image

- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/mgw/config.go
This PR fixes an issue where JWT token issuers are overridden when there are multiple issuers in the shared mode.
Fixes https://github.com/wso2/k8s-api-operator/issues/453
> [1.3.x] Preventing JWT token issuers getting overridden in shared mode

- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/mgw/config.go
This PR fixes an issue where JWT token issuers are overridden when there are multiple issuers in the shared mode.
Fixes https://github.com/wso2/k8s-api-operator/issues/453
> Preventing JWT token issuers getting overridden in shared mode

- api-operator/deploy/controller-configs/controller_conf.yaml
- api-operator/pkg/mgw/api.go
- api-operator/pkg/mgw/deployment.go
This PR adds hostAlias support of Operator which allows pod/deployment level override of hostname resolution when DNS and other options are not applicable.
Host Aliases can be defined under `mgw-deployment-configs`.
```
hostAliases: |
- ip: "34.23.234.43"
hostnames:
- "wso2km"
- "km.wso2.com"
```
Fixes https://github.com/wso2/k8s-api-operator/issues/466
> HostAlias support for Operator

- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/endpoints/sidecar.go
- api-operator/pkg/mgw/deployment.go
Resolves #468 
Create a local instance of the containersList for each call to the reconcile loop, instead of using the same global one.
Use local instance of ContainersList
N/A
> Do not use global variable for containerslist

- api-operator/pkg/swagger/endpoints.go
- api-operator/pkg/swagger/extensions.go
This PR adds `x-wso2-endpoints` support for the Operator. With this, we can define endpoints in the swagger definition in the following format.
```
x-wso2-production-endpoints: "#/x-wso2-endpoints/myEndpoint1" 
x-wso2-endpoints:
- myEndpoint1:
urls:
- https://petstore.swagger.io/v2
```
Scenarios tested: 1,2,7,8
Fixes https://github.com/wso2/k8s-api-operator/issues/473
Related issues: https://github.com/wso2/k8s-api-operator/issues/415, https://github.com/wso2/k8s-api-operator/issues/352
> x-wso2-endpoints support for Operator

- api-operator/deploy/controller-configs/controller_conf.yaml
- api-operator/pkg/k8s/mount.go
- api-operator/pkg/mgw/deployment.go
- api-operator/pkg/mgw/uservolumes.go
Related to #470 
A new boolean field `asEnvVar` has been added in the structure of the mgw-deployment-configs configmap. 
If this field is true for a ConfigMap or Secret, the values in the ConfigMap / secrets will be declared as environment variables instead of mounting the configmap / secret as a volume.
```
apiVersion: v1
kind: ConfigMap
metadata:
name: mgw-deployment-configs
namespace: micro
data:
mgwConfigMaps: |
- name: test2cm
mountLocation: /home/ballerina/test2cm
subPath: test2cm
namespace: micro
- name: test2cmEnv
asEnvVar: true
mgwSecrets: |
- name: test1secret
mountLocation: /home/ballerina/test1secret
subPath: test1secret
- name: test1secretEnv
asEnvVar: true
```
N/A
> Create environment variables from ConfigMap / Secret

- docs/HowToGuide/production-deployment-guide.md
- docs/Readme.md
This PR adds docs related to moving from a lower environment to a higher environment in a production scenario.
Related Issues: https://github.com/wso2/k8s-api-operator/issues/415, https://github.com/wso2/k8s-api-operator/issues/352
> Add Production Deployment Guide

- api-operator/cmd/manager/main.go
- api-operator/deploy/controller-artifacts/operator.yaml
- api-operator/pkg/analytics/config.go
- api-operator/pkg/config/system.go
- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/controller/api/constants.go
- api-operator/pkg/controller/ratelimiting/ratelimiting_controller.go
- api-operator/pkg/controller/targetendpoint/constants.go
- api-operator/pkg/controller/targetendpoint/targetendpoint_controller.go
- api-operator/pkg/endpoints/sidecar.go
- api-operator/pkg/kaniko/docker.go
- api-operator/pkg/mgw/api.go
- api-operator/pkg/mgw/config.go
- api-operator/pkg/mgw/hpa.go
- api-operator/pkg/mgw/ingress.go
- api-operator/pkg/mgw/route.go
- api-operator/pkg/mgw/uservolumes.go
- api-operator/pkg/mgw/virtualservice.go
- api-operator/pkg/registry/registry.go
- api-operator/pkg/security/const.go
- api-operator/pkg/security/default.go
Set system namespace with the environment variable: `SYSTEM_NAMESPACE`
Add new package `config` for global configs
- Tested scenario 2 with `SYSTEM_NAMESPACE = foo-sys` namespace
- Tested scenario 6 without defining `SYSTEM_NAMESPACE` variable
Get `SYSTEM_NAMESPACE` from environment variable and set it to `config.SystemNamespace` global variable with enabling to all other packages to access it.
Change `SYSTEM_NAMESPACE` in operator.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: api-operator
namespace: wso2-system
spec:
replicas: 1
selector:
matchLabels:
name: api-operator
template:
metadata:
labels:
name: api-operator
spec:
serviceAccountName: api-operator
containers:
- name: api-operator
image: wso2/k8s-api-operator:1.2.2
command:
- api-operator
imagePullPolicy: Always …
```
> [1.2.x] Set system namespace with the environment variable "SYSTEM_NAMESPACE"

- api-operator/deploy/controller-configs/controller_conf.yaml
- api-operator/deploy/controller-configs/mgw_conf_mustache.yaml
- api-operator/pkg/mgw/config.go
Operator has throttling configuration in two places. In apim_conf.yaml and in mgw_conf_mustache.yaml where are hard coded values for two endpoints.
I want to be able to configure all throttling endpoints in one place.
I added new configuration parameters to be able configure all throttling endpoints in one place.
> Ability to configure all throttling endpoints

- api-operator/pkg/apim/deleteAPI.go
- api-operator/pkg/apim/importAPI.go
In the original PR a configMap with an API definition must use same name as API CRD itself. I added possibility to use different name for an API CRD and a configMap with Swagger.
I use the SwaggerConfigNames array from the API class to iterate through all defined API in CRD
#488
> itterate through all api definition

- api-operator/deploy/controller-configs/mgw_conf_mustache.yaml
- api-operator/deploy/crds/wso2.com_securities_crd.yaml
- api-operator/go.sum
- api-operator/pkg/apis/wso2/v1alpha1/security_types.go
- api-operator/pkg/mgw/config.go
- api-operator/pkg/security/security.go
We want to use a JWK endpoint for a IdP public key instead of a secret with hardcoded certificate. It will allow us to easily rotate certificates in the IdP
Ability to configure a JWK endpoint in Security CRD instead of a certificate.
Added new attribute to the Security CRD. Than add certificate or JWK endpoint to microgw conf mustache
#478
> ability to configure JWK endpoint for JWT instead of certificate

- api-operator/pkg/mgw/deployment.go
In K8s cluster we already have a Prometheus server. But this server scrape only pods with prometheus.io/scrape=true annotation. When I enable observability in the operator config it exposes Prometheus port but doesn't add annotations. Then I don't see any wso2 MGW metrics in the Prometheus.
> Added prometheus annotations to deployment

- api-operator/deploy/crds/wso2.com_integrations_crd.yaml
- api-operator/pkg/apis/wso2/v1alpha1/integration_types.go
- api-operator/pkg/apis/wso2/v1alpha1/zz_generated.deepcopy.go
- api-operator/pkg/controller/integration/integration_deployment.go
> Add support of `configMapRef` and `secretRef` into the Integration CRD. 
Fixes: https://github.com/wso2/devstudio-tooling-ei/issues/1306
> Add envFrom support for the integration CRD

- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/kaniko/job.go
- api-operator/pkg/mgw/config.go
- api-operator/pkg/mgw/deployment.go
- api-operator/pkg/registry/amazon_ecr.go
- api-operator/pkg/registry/dockerhub.go
- api-operator/pkg/registry/gcr.go
- api-operator/pkg/registry/http.go
- api-operator/pkg/registry/https.go
- api-operator/pkg/registry/https_test.go
- api-operator/pkg/registry/quay.go
- api-operator/pkg/registry/registry.go
- api-operator/pkg/registry/utils/utils.go
Because of global variables in the registry package, when the Operator restarts and several `API` resources exist, the operator will mix the image names between all APIs. As a result, all micro-gateways are deployed with the same image name (the one that was written last in the global variable)
I was able to test the case with  a GCR registry, but not with other registries.
Fixes #461
> Remove global variables from registry package

- api-operator/deploy/controller-configs/controller_conf.yaml
- api-operator/deploy/controller-configs/mgw_conf_mustache.yaml
- api-operator/pkg/mgw/config.go
Allow to configure if tracing is enabled in apim configuration. Currently only direct modification in mgw_conf-mustache can enable tracing.
Allow to configure observability and tracing in the same way.
> Enable jaeger tracing from config

- api-operator/deploy/controller-artifacts/operator.yaml
Add resource limits for API Operator
fixes https://github.com/wso2/k8s-api-operator/issues/522
```
resources:
requests:
memory: "250Mi"
cpu: "250m"
limits:
memory: "500Mi"
cpu: "500m"
```
> Add resource limits for API Operator

- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/mgw/virtualservice.go
When the operator mode is ISTIO it creates ISTIO virtual service with match -> url -> prefix where prefix is from swagger where I have in base path something like /api/{version} when I update information in swagger and update CRD API everything is update except virtual service which already exists. Result is that ISTI can route requests only to previous version but MGW knows only updated version.
> Virtual service update

- api-operator/pkg/controller/security/security_controller.go
There is a bug when you use JWKS you don't need to have a secret with IdP certificate. But the operator still checks this. I added check if JWKS is defined than secret is not check.
> check security for credentials only if JWKS is not defined

- README.md
README.md needs to be updated about minikube url used in CURL command. 
No need of replacing <EXTERNAL_IP> with minikube output. We can use whole url to test the microservice.
#527
> Updated minikube url used in curl command

- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/controller/api/constants.go
- api-operator/pkg/kaniko/job.go
- api-operator/pkg/registry/dockerhub.go
- api-operator/pkg/registry/registry.go
- api-operator/pkg/registry/utils/consts.go
In our corporation we use an internal docker registry (Nexus3). In the registry we store our internal images and use it as proxy for images from public sources. We divide our registry to two. One is only for pulling and contains all internal images and all images through proxy. Second is used for pushing to our internal store and is unable to pull through proxied registries.
We also have our internal private cloud with K8s clusters where we want to use API Operator. In these clusters images can be pulled only from our internal registry and they cannot connect to internet directly. In each cluster is already defined secret with registry pull credentials.
https://github.com/wso2/k8s-api-operator/issues/463
You can optionally configure your name of secret with pull credentials instead of …
> Allow user to configure name of secret with credentials to registry and allow to use different registry for pull and push

- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/controller/ratelimiting/ratelimiting_controller.go
- api-operator/pkg/controller/security/security_controller.go
- api-operator/pkg/controller/targetendpoint/targetendpoint_controller.go
No need of configuring pod watches. Only API resources need to be watched.
Remove all pod watches.
#533
> remove unwanted pod watches

- api-operator/pkg/registry/https_test.go
No need of using assert package in http_test as this test can be implemented using go "testing"  package.
Remove assert import from https_test and use t.Log() & t.Error() for logging.
#539
> Remove assert package from https_test

- api-operator/pkg/controller/api/api_controller.go
Default jwt token was not using accordingly for the api resources(resource level) which do not contain any custom jwt security token (security policy).
Api resources without any custom jwt security token defined, need to use the default jwt security token (security policy).
#532
> Fixed adding default jwt token

- api-operator/pkg/controller/integration/integration_controller.go
- api-operator/pkg/k8s/client.go
Fixes: https://github.com/wso2/k8s-api-operator/issues/571
Approach: I faced issue [1], as we have a `-` in the service name. As a workaround, I get the existing service object, extract required parameters and update the service object created from the updated configs. 
Also removed an unwanted INFO level log that prints when reconsile loop hits. 
[1]. https://github.com/kubernetes/kubernetes/issues/36072
> Fix [apim-k8s-571] service is not updated when updating an existing deployment

- api-operator/pkg/controller/integration/integration_functions.go
> $subject. Since config maps are configured in the operator namespace.
> Get integration config maps from the server namespace

- api-operator/deploy/controller-artifacts/operator.yaml
- api-operator/deploy/crds/wso2.com_integrations_crd.yaml
- api-operator/pkg/apis/wso2/v1alpha2/integration_types.go
- api-operator/pkg/controller/integration/integration_deployment.go
- distribution/pom.xml
- pom.xml
Give capability to WSO2 API Operator to support volume mounts and also to change the ImagePullPolicy as well.
Fixes: https://github.com/wso2-enterprise/wso2-apim-internal/issues/67
> Give capability to WSO2 API Operator to support volumeMounts

- api-operator/deploy/crds/wso2.com_integrations_crd.yaml
- api-operator/pkg/apis/wso2/v1alpha2/integration_types.go
- api-operator/pkg/controller/integration/integration_deployment.go
With this feature, we are providing the capability to, 
1. Support volumeMounts to deploy(replace existing) config files without
the need to change the image by using config maps.
2. Change image pull policy to either Always, Never or IfNotPresent.
3. Add Node Affinity / Anti-Affinity
4. Add Pod Affinity / Anti Affinity
Feature completes with: https://github.com/wso2/k8s-api-operator/pull/613
Fixes: https://github.com/wso2/api-manager/issues/247
> Provide support for Node-Affinity/Anti-Affinity
