wso2/k8s-api-operator

- apim-operator/deploy/crds/wso2_v1alpha1_targetendpoint_cr.yaml
- apim-operator/deploy/crds/wso2_v1alpha1_targetendpoint_crd.yaml
- apim-operator/pkg/apis/wso2/v1alpha1/targetendpoint_types.go
- apim-operator/pkg/controller/add_targetendpoint.go
- apim-operator/pkg/controller/targetendpoint/targetendpoint_controller.go
> adding target endpoint

- apim-operator/pkg/apis/addtoscheme_wso2_v1alpha1.go
- apim-operator/pkg/apis/wso2/v1alpha1/zz_generated.openapi.go
- apim-operator/pkg/controller/ratelimiting/ratelimiting_controller.go
- apim-operator/vendor/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/test_setup.go
- apim-operator/vendor/github.com/operator-framework/operator-sdk/internal/util/projutil/project_util.go
> moving to wso2 space

- apim-operator/cmd/manager/main.go
- apim-operator/deploy/crds/wso2_v1alpha1_targetendpoint_cr.yaml
- apim-operator/deploy/operator.yaml
- apim-operator/pkg/controller/add_api.go
- apim-operator/pkg/controller/add_ratelimiting.go
- apim-operator/pkg/controller/add_targetendpoint.go
- apim-operator/pkg/controller/targetendpoint/targetendpoint_controller.go
- apim-plugin/kubectl-add.sh
> adding improvements

- apim-operator/pkg/controller/api/api_controller.go
> Adding balx generating Pod along with the init container and ballerina runtime image app container
> Link to the PR for changes …
> Adding init container and balx container

- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
> Adding Kaniko pod and MGW deployment

- resources/Dockerfile
> Adding reference Dockerfile to be used by Kaniko

- apim-plugin/kubectl-add.sh
> adding support for replicas

- apim-operator/deploy/controller_conf.yaml
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
Controller configmap was added and it was handled in api-controller.
Swagger handling was moved under a separate function
> Adding controller configmap

- apim-operator/Gopkg.lock
- apim-operator/deploy/crds/wso2_v1alpha1_security_cr.yaml
- apim-operator/deploy/crds/wso2_v1alpha1_security_crd.yaml
- apim-operator/deploy/operator.yaml
- apim-operator/pkg/apis/wso2/v1alpha1/security_types.go
- apim-operator/pkg/apis/wso2/v1alpha1/zz_generated.openapi.go
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/security/security_controller.go
> Adding new fields to security kind

- README.md
- apim-operator/deploy/crds/wso2_v1alpha1_api_cr.yaml
- apim-operator/deploy/crds/wso2_v1alpha1_api_crd.yaml
- apim-operator/deploy/crds/wso2_v1alpha1_ratelimiting_crd.yaml
- apim-operator/deploy/crds/wso2_v1alpha1_security_crd.yaml
- apim-operator/deploy/crds/wso2_v1alpha1_targetendpoint_cr.yaml
- apim-operator/deploy/operator.yaml
- apim-operator/pkg/apis/wso2/v1alpha1/api_types.go
- apim-operator/pkg/apis/wso2/v1alpha1/targetendpoint_types.go
- apim-operator/pkg/apis/wso2/v1alpha1/zz_generated.openapi.go
- apim-operator/pkg/controller/targetendpoint/targetendpoint_controller.go
- apim-plugin/kubectl-add.sh
> adding changes to target endpoint

- apim-operator/pkg/controller/api/api_controller.go
> Adding k8s job for Kaniko pod.

- apim-operator/build/controller_resources/Dockerfile
- apim-operator/pkg/controller/api/api_controller.go
- resources/Dockerfile
Read image names, docker registry etc values from the global configmap defined by the users to fill in the necessary controller values.
And toolkit image has been pushed to the docker registry "wso2am" with the name "wso2micro-gw-toolkit" and version "3.0.0-beta-2". Dockerfile in Kaniko will use this image to build the micro-gw-executable file.
> Brief description of the …
> Reading values from global config and fill the controller.

- apim-operator/deploy/crds/default_security_cr.yaml
- apim-operator/deploy/crds/wso2_v1alpha1_security_cr.yaml
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
- apim-operator/pkg/controller/security/security_controller.go
> Getting security object name from the swagger and if it is not defined use default security 
> Link to the PR for changes to …
> reading swagger input and adding default security

- README.md
- apim-operator/deploy/crds/wso2_v1alpha1_api_cr.yaml
- apim-operator/deploy/crds/wso2_v1alpha1_api_crd.yaml
- apim-operator/pkg/apis/wso2/v1alpha1/api_types.go
- apim-operator/pkg/apis/wso2/v1alpha1/zz_generated.openapi.go
- apim-plugin/kubectl-add.sh
> making changes to api crd definition

- apim-operator/deploy/controller_conf.yaml
- apim-operator/deploy/crds/default_security_cr.yaml
- apim-operator/deploy/crds/wso2_v1alpha1_api_cr.yaml
- apim-operator/deploy/crds/wso2_v1alpha1_api_crd.yaml
- apim-operator/deploy/crds/wso2_v1alpha1_security_crd.yaml
- apim-operator/deploy/operator.yaml
- apim-operator/deploy/role.yaml
- apim-operator/pkg/controller/api/api_controller.go
> Fixing operator flow

- apim-operator/build/Dockerfile
- apim-operator/build/dockerSecretTemplate.mustache
- apim-operator/deploy/operator.yaml
- apim-operator/pkg/controller/api/api_controller.go
Automate the docker-config creation by reading docker credentials from the secret and create a docker-config in the needed format using a template
> Automating the docker-config creation

- README.md
- apim-operator/deploy/operator.yaml
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
- resources/Dockerfile
> Improved readme while testing the flow. Hence included the necessary artefacts deployments along with he
> Link to the PR for …
> Improving ReadMe

- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
Handles default volume mounts and if analytics is enabled, mounts the analytics certificate to the kaniko job
> Handling dynamic volume mounts for kaniko job

- apim-operator/Gopkg.lock
- apim-operator/build/Dockerfile
- apim-operator/build/controller_resources/Dockerfile
- apim-operator/build/controller_resources/dockerFile.mustache
- apim-operator/deploy/controller_conf.yaml
- apim-operator/deploy/crds/wso2_v1alpha1_api_cr.yaml
- apim-operator/deploy/crds/wso2_v1alpha1_api_crd.yaml
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
> adding security certificates to ballerina truststore …
> Adding certificates to truststore 

- apim-operator/build/controller_resources/dockerFile.mustache
- apim-operator/deploy/controller-artifacts/operator.yaml
- apim-operator/deploy/controller-configs/default_security_cr.yaml
- apim-operator/deploy/sample-crs/wso2_v1alpha1_api_cr.yaml
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
- apim-operator/pkg/controller/security/security_controller.go
> include the truststore password in a secret to make it secure.  …
> adding secret to fetch truststore password

- apim-operator/deploy/controller-artifacts/operator.yaml
- apim-operator/deploy/crds/wso2_v1alpha1_api_crd.yaml
- apim-operator/pkg/controller/api/api_controller.go
Adding LB type service to the API controller
Removing unnecessary required fields in API CRD
Removing unnecessary methods in API controller
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no …
> Adding LB service to the API controller.

- README.md
Adding the command to readme file to expose the API in k8s cluster using k8s extension command.
> Link to the PR for changes to …
> Adding kubectl add api command to ReadMe.

- apim-operator/pkg/controller/api/api_controller.go
This PR fixes the issue https://github.com/wso2/k8s-apim-operator/issues/44
Also this fixes the issue of operator stopping when it erroneously detect the available controller config artifacts are unavailable.
> Check the availability of docker image and schedule job if image is not found

- apim-operator/build/controller_resources/dockerFile.gotmpl
- apim-operator/build/microgwconf.mustache
- apim-operator/deploy/controller-artifacts/operator.yaml
- apim-operator/deploy/controller-configs/controller_conf.yaml
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
Initial testing had been done using micro-gw 3.0.0 beta 2 version. The improved and latest version of micro-gateway (which is 3.0.1 ) is now available. Hence the controller and its associated resources were updated to be compatible with 3.0.1
> Link(s) to product documentation that …
> Migrating the micro-gw from 3.0.0 beta2 to 3.0.1 GA.

- apim-operator/build/microgwconf.mustache
- apim-operator/deploy/apim-analytics-configs/apim_analytics_conf.yaml
- apim-operator/deploy/apim-analytics-configs/apim_analytics_host_mapping.yaml
- apim-operator/deploy/apim-analytics-configs/apim_analytics_secret_template.yaml
- apim-operator/deploy/sample/wso2_v1alpha1_security_cr.yaml
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
>This PR fixes the OAuth2 flow. Tested with beta2 and 3.0.1GA. Fixes the issue https://github.com/wso2/k8s-apim-operator/issues/53
> Fixing OAuth2 flow

- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/ratelimiting/ratelimiting_controller.go
This PR fixes the issue https://github.com/wso2/k8s-apim-operator/issues/58
Earlier when the user deletes an api or the operator; the related services, configmaps, secrets, jobs and other resources are not deleted. User had to manually clean up all the garbage resources. This PR allows the operator to handle cascade deletion of dependents of the api instance, so that the resources are not orphaned.
> `kubectl delete api <api-name> -n <namespace>` would delete all resources related to the api instance 
> `kubectl delete deployment apim-operator -n wso2-system ` would delete all resources related to the operator
> Handling deletion of an API and operator

- README.md
> Adding security flow
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
> updating readme with security flow

- apim-operator/pkg/controller/api/api_controller.go
> enabling the usage of apim configurations when required  …
> making apim configurations optional

- apim-operator/README.md
- distribution/assembly.xml
- distribution/pom.xml
- pom.xml
> creating a zip with deployment artifacts.
adding developer guide to build the image after changes added. 
> Link to the PR for …
> creating a zip with deployment artifacts and adding developer guide

- apim-operator/Gopkg.lock
- apim-operator/deploy/controller-artifacts/operator.yaml
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
> docker template need to make available for the user so that he can customize the docker file. Adding a new port to the load balancer service.  
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …
> making docker file template available for the user in a configmap and adding multiple ports to the load balancer service

- apim-operator/deploy/controller-configs/controller_conf.yaml
- apim-operator/pkg/controller/api/api_controller.go
> adding values to the fields relevant to the HPA in controller-config and change the the image name to API name
> Link to the PR …
> Adding values to controller conf  fields relevant to the HPA and changing the image name to API name

- toolkit-docker-image/Dockerfile
- toolkit-docker-image/ReadMe.md
> Adding MGW Toolkit Image and instruction to build

- apim-operator/pkg/controller/api/api_controller.go
> Earlier when using default security flow it was not update the relevant fields on configuration file. Fixing that issue.
> When updating an API, modifying the flow to keep updating swagger definitions and initial swagger definition  in a separate configmaps  and keep one modified swagger for mgw for all updates. 
> Brief description of the new feature or bug fix as it …
> Fixing default security flow and modifying updating API flow

- apim-operator/deploy/controller-configs/controller_conf.yaml
- apim-operator/pkg/controller/api/api_controller.go
Once the deployment in place, we need to make sure that the deployment/pod is ready to accept/server the traffic. Further, if the pod is unhealthy, it needs to be automatically spawned/restarted. 
Introduce liveness prob and readiness probe for the deployment.
> …
> Adding readiness and liveness probes to the mgw deployment.

- apim-operator/build/dockerSecretTemplate.mustache
- apim-operator/deploy/controller-artifacts/operator.yaml
- apim-operator/deploy/controller-configs/docker_secret_mustache.yaml
- apim-operator/deploy/controller-configs/mgw_conf_mustache.yaml
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
Moving docker-conf to a k8s configmap.
Updating docker image for the apim-operator
DevOp will have the control to change the docker conf template if necessary
Removing existing docker-conf template/mustache and moving the template to a k8s configmap
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in …
> Moving docker conf mustache to k8s configmap

- apim-operator/deploy/controller-configs/docker_template_conf.yaml
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
> This feature adding support to modify request and response flows with custom interceptors. 
> Link to the PR for changes to the …
> Adding support for interceptors 

- apim-operator/deploy/crds/wso2_v1alpha1_api_crd.yaml
- apim-operator/pkg/apis/wso2/v1alpha1/api_types.go
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
> This feature enabling the support of interceptors to modify request and response flows when updating the API
> Link to the PR …
> Adding support for interceptors when updating API

- apim-operator/pkg/controller/api/api_controller.go
> Fixing the updating flow with volume mount, when handling interceptors …
> Fixing updating flow when handling interceptors

- README.md
> Improving ReadMe file.

- distribution/assembly.xml
- distribution/pom.xml
> Modifying assembly file.

- README.md
- distribution/pom.xml
> Bumping  version to v1.0.0-alpha.

- scenarios/scenario-2/petstore_security_basic.yaml
> Correcting minor version issue in sample scenario.

- apim-operator/deploy/controller-artifacts/operator.yaml
- apim-operator/pkg/controller/api/api_controller.go
Resolves issue #122 
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” …
> Create service if not available for update api command.

- apim-operator/deploy/crds/wso2_v1alpha1_api_crd.yaml
- apim-operator/pkg/apis/wso2/v1alpha1/api_types.go
- apim-operator/pkg/apis/wso2/v1alpha1/zz_generated.openapi.go
- apim-operator/pkg/controller/api/api_controller.go
- scenarios/scenario-4/oauth-security.yaml
If we do configuration changes to mgw, then there's no way to build and push the docker image for the same swagger definition as per the current implementation. Because current implementation does not build the image if it exists in the docker registry. Hence introducing a flag with build the image again even if the image exists in the docker registry.
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a …
> Introducing override property to build image even though it exists

- scenarios/README.md
Updating readme of scenarios
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
> Updating readme of scenarios

- install/api-manager/k8s-artifacts/wso2apim-configmap.yaml
- install/api-manager/k8s-artifacts/wso2apim-deployment.yaml
- scenarios/scenario-3/README.md
> Updating API portal image.

- docs/HowToGuide/apply-security-to-api.md
- scenarios/README.md
- scenarios/scenario-10/README.md
- scenarios/scenario-10/interceptor_swagger.yaml
- scenarios/scenario-10/modifyResponse.bal
- scenarios/scenario-10/validateQueryPrams.bal
> Adding readme guide on applying interceptors to the API …
> Adding readme guide for apply interceptors to the API

- scenarios/scenario-7/README.md
- scenarios/scenario-8/README.md
> Updated README.MD

- README.md
- scenarios/scenario-5/README.md
> Updating the main README.md with latest information.
> The following screenshots show the directory path and its containings.
So I edited the main README.md because, previously it contained a different path.
> Updating the main README.md file

- scenarios/scenario-6/README.md
- scenarios/scenario-6/five-req-policy.yaml
- scenarios/scenario-6/swagger.yaml
> scenario 6 policy renaming.

- scenarios/scenario-1/README.md
- scenarios/scenario-2/swagger.yaml
- scenarios/scenario-3/swagger.yaml
- scenarios/scenario-4/swagger.yaml
- scenarios/scenario-5/swagger.yaml
- scenarios/scenario-6/swagger.yaml
- scenarios/scenario-7/swagger.yaml
- scenarios/scenario-8/swagger.yaml
- scenarios/scenario-9/swagger.yaml
> Making swagger's API name and the command's API same.

- apim-operator/deploy/controller-artifacts/operator.yaml
- apim-operator/deploy/controller-configs/controller_conf.yaml
- apim-operator/deploy/kubectl-extensions/kubectl-add
- apim-operator/deploy/kubectl-extensions/kubectl-update
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
> Making readiness and liveness configurable.

- apim-operator/deploy/controller-configs/controller_conf.yaml
- k8s-artifacts/api-portal/wso2apim-deployment.yaml
- scenarios/scenario-1/products_swagger.yaml
- scenarios/scenario-2/swagger.yaml
- scenarios/scenario-3/swagger.yaml
- scenarios/scenario-4/swagger.yaml
- scenarios/scenario-5/swagger.yaml
- scenarios/scenario-6/swagger.yaml
- scenarios/scenario-7/swagger.yaml
- scenarios/scenario-8/swagger.yaml
- scenarios/scenario-9/swagger.yaml
> Changing Samples

- scenarios/scenario-1/products_swagger.yaml
> Fixing the APIstore swagger loading issue

- README.md
- docs/GettingStarted/overview.md
- docs/GettingStarted/quick-start-guide.md
- docs/HowToGuide/configurations-overview.md
- docs/HowToGuide/enable-analytics-to-api.md
- docs/HowToGuide/perform-api-operations.md
- docs/Readme.md
> Updating the docs

- README.md
- scenarios/scenario-10/README.md
- scenarios/scenario-11/README.md
> Updating the readme files of scenario 10 and 11

- docs/HowToGuide/work-with-endpoints.md
- docs/HowToGuide/working-with-endpoints.md
- docs/Readme.md
> added target endpoint documentation

- apim-operator/deploy/controller-artifacts/operator.yaml
- docs/HowToGuide/apply-security-to-api.md
- docs/HowToGuide/configure-apictl-tool.md
- docs/HowToGuide/enable-analytics-to-api.md
- docs/HowToGuide/perform-api-operations.md
- docs/HowToGuide/using-kubectl-extensions.md
- docs/HowToGuide/working-with-endpoints.md
- k8s-artifacts/api-portal-with-analytics/api-analytics/analytics-dashboard-deployment.yaml
- k8s-artifacts/api-portal-with-analytics/api-analytics/analytics-worker-deployment.yaml
- k8s-artifacts/api-portal-with-analytics/api-portal/wso2apim-deployment.yaml
- k8s-artifacts/api-portal/wso2apim-deployment.yaml
> Improving ReadMe files.

- apim-operator/deploy/kubectl-extensions/kubectl-add
- apim-operator/deploy/kubectl-extensions/kubectl-update
- docs/HowToGuide/using-kubectl-extensions.md
Allow the kubectl extension to add/update API from an API project with interceptors.
Add --override property
> Modifying kubectl extensions

- README.md
- docs/GettingStarted/quick-start-guide.md
> Adding collapsible markdown to ReadMes

- README.md
- docs/GettingStarted/quick-start-guide.md
> Minor readme formatting issues.

- README.md
- docs/GettingStarted/quick-start-guide.md
- docs/HowToGuide/using-kubectl-extensions.md
- scenarios/scenario-5/README.md
> Improving docs.

- README.md
- distribution/pom.xml
- docs/GettingStarted/quick-start-guide.md
- docs/HowToGuide/configurations-overview.md
- docs/HowToGuide/using-kubectl-extensions.md
- docs/HowToGuide/working-with-endpoints.md
- pom.xml
- scenarios/scenario-1/README.md
- scenarios/scenario-11/README.md
- scenarios/scenario-2/README.md
- scenarios/scenario-3/README.md
- scenarios/scenario-4/README.md
- scenarios/scenario-5/README.md
- scenarios/scenario-6/README.md
- scenarios/scenario-7/README.md
- scenarios/scenario-8/README.md
- scenarios/scenario-9/README.md
> Bump version to 1.0.1

- scenarios/scenario-9/target-ep-inv.yaml
- scenarios/scenario-9/target-ep-prod.yaml
- scenarios/scenario-9/target-ep-rev.yaml
> Fixing scenario 9 issue with load balancing

- apim-operator/pkg/controller/api/api_controller.go
> Disable the sidecar injection for kaniko job.
> With this annotation support, operator can run kaniko jobs in a Istio enabled environment. …
> Disable sidecar injection for kaniko job

- README.md
- scenarios/README.md
- scenarios/scenario-13/README.md
- scenarios/scenario-13/S01-APIM_for_Istio_Services/README.md
- scenarios/scenario-13/S01-APIM_for_Istio_Services/microservices.yaml
- scenarios/scenario-13/S01-APIM_for_Istio_Services/swagger.yaml
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/README.md
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/gateway.yaml
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/microservices.yaml
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/swagger.yaml
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/virtualservice.yaml
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/README.md
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/microgw/mg.yaml
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/microgw/products_swagger.yaml
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/products/products_dep.yaml
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/wso2-gateway.yaml
Adding Istio Samples
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable …
> Adding Istio scenario samples

- README.md
> Updating install using the directory

- README.md
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/vendor/github.com/getkin/kin-openapi/openapi2/openapi2.go
- apim-operator/vendor/github.com/getkin/kin-openapi/openapi2conv/openapi2_conv.go
- apim-operator/vendor/modules.txt
Adding Swagger v2 Support
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
> Adding Swagger v2 support

- README.md
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/vendor/github.com/getkin/kin-openapi/openapi2/openapi2.go
- apim-operator/vendor/github.com/getkin/kin-openapi/openapi2conv/openapi2_conv.go
- apim-operator/vendor/modules.txt
- k8s-artifacts/api-portal-with-analytics/api-analytics/analytics-dashboard-conf-configmap.yaml
- k8s-artifacts/api-portal-with-analytics/api-analytics/analytics-dashboard-deployment.yaml
- k8s-artifacts/api-portal-with-analytics/api-analytics/analytics-dashboard-service.yaml
- k8s-artifacts/api-portal-with-analytics/api-analytics/analytics-worker-conf-configmap.yaml
- k8s-artifacts/api-portal-with-analytics/api-analytics/analytics-worker-deployment.yaml
- k8s-artifacts/api-portal-with-analytics/api-portal/wso2apim-configmap.yaml
- k8s-artifacts/api-portal-with-analytics/api-portal/wso2apim-deployment.yaml
- k8s-artifacts/api-portal-with-analytics/api-portal/wso2apim-service.yaml
- k8s-artifacts/api-portal/wso2apim-configmap.yaml
- k8s-artifacts/api-portal/wso2apim-deployment.yaml
- k8s-artifacts/api-portal/wso2apim-service.yaml
> K8s artifacts for APIM v3 rc1

- apim-operator/deploy/controller-configs/controller_conf.yaml
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
User might want to pass some additional parameters to the kaniko job, depending on the requirements. To get images from cache repo, to not to push the image etc.(https://github.com/GoogleContainerTools/kaniko#additional-flags)
Introducing a configmap called "kaniko-arguments" where you can pass the additional flags. …
> Introducing kaniko additional flags.

- apim-operator/deploy/controller-configs/controller_conf.yaml
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
> Add TLS support for ingress 

- docs/HowToGuide/working-with-kaniko-additional-flags.md
- docs/Readme.md
ReadMe on how to work with additional kaniko flags. …
> Readme for additional kaniko flags.

- apim-operator/pkg/controller/targetendpoint/targetendpoint_controller.go
- scenarios/scenario-14/README.md
- scenarios/scenario-14/hello-world-serverless.yaml
- scenarios/scenario-14/swagger.yaml
> Update serverless feature to latest Knative version v0.13

- apim-operator/deploy/controller-configs/controller_conf.yaml
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
> change ingress configs

- apim-operator/pkg/controller/api/api_controller.go
fix #237 
- Reinitialize variables in reconcile loop
> Reinitialize variables in reconcile loop

- apim-operator/deploy/controller-configs/controller_conf.yaml
- k8s-artifacts/api-portal-with-analytics/api-analytics/analytics-dashboard-conf-configmap.yaml
- k8s-artifacts/api-portal-with-analytics/api-analytics/analytics-worker-conf-configmap.yaml
- k8s-artifacts/api-portal-with-analytics/api-portal/wso2apim-configmap.yaml
Changed the Mysql driver name and removed wso2 dependency. …
> Changed Mysql driver name

- apim-operator/deploy/controller-configs/controller_conf.yaml
- apim-operator/pkg/controller/api/api_controller.go
> Add HTTP health check

- README.md
- apim-operator/deploy/controller-artifacts/operator.yaml
- apim-operator/pkg/controller/api/api_controller.go
- distribution/pom.xml
- docs/HowToGuide/configurations-overview.md
- docs/HowToGuide/using-kubectl-extensions.md
- k8s-artifacts/api-portal-with-analytics/api-portal/wso2apim-deployment.yaml
- k8s-artifacts/api-portal/wso2apim-deployment.yaml
- pom.xml
- scenarios/README.md
- scenarios/scenario-1/README.md
- scenarios/scenario-15/README.md
- scenarios/scenario-2/README.md
- scenarios/scenario-3/README.md
- scenarios/scenario-4/README.md
- scenarios/scenario-5/README.md
- scenarios/scenario-6/README.md
- scenarios/scenario-7/README.md
- scenarios/scenario-8/README.md
- scenarios/scenario-9/README.md
> Preparing for the alpha2 release

- apim-operator/deploy/controller-configs/dockerfile_template.yaml
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
- Handle multiple java interceptor volumes
> Handle multiple java interceptor volumes

- scenarios/scenario-5/oauth-security.yaml
> Fixing api manager server endpoint

- README.md
> Removing folder installation option

- apim-operator/pkg/controller/api/api_controller.go
> Add per api ingress support

- scenarios/scenario-14/swagger.yaml
- scenarios/scenario-17/README.md
- scenarios/scenario-17/hello-world-service.yaml
- scenarios/scenario-17/swagger.yaml
> Add Ingress Sample

- k8s-artifacts/api-portal-with-analytics/api-analytics/analytics-dashboard-deployment.yaml
- k8s-artifacts/api-portal-with-analytics/api-analytics/analytics-worker-deployment.yaml
- k8s-artifacts/api-portal-with-analytics/api-portal/wso2apim-deployment.yaml
- k8s-artifacts/api-portal/wso2apim-deployment.yaml
- Updated apim and analytics docker images
> Updated apim and analytics docker images

- README.md
- apim-operator/deploy/controller-configs/controller_conf.yaml
- distribution/pom.xml
- docs/HowToGuide/configurations-overview.md
- docs/HowToGuide/working-with-endpoints.md
- docs/Troubleshooting/troubleshooting.md
- scenarios/scenario-10/README.md
- scenarios/scenario-12/README.md
- scenarios/scenario-13/S01-APIM_for_Istio_Services/README.md
- scenarios/scenario-14/README.md
- scenarios/scenario-16/README.md
- Rename `api-k8s-crds-1.1.0-alpha2` to `k8s-api-operator-1.1.0-beta`
- Update scenario readme files
> Update version value for the release release 1.1.0 beta

- README.md
- apim-operator/deploy/controller-artifacts/operator.yaml
- scenarios/scenario-10/interceptor_swagger.yaml
- scenarios/scenario-12/swagger.yaml
- scenarios/scenario-13/S01-APIM_for_Istio_Services/swagger.yaml
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/swagger.yaml
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/microgw/products_swagger.yaml
- scenarios/scenario-14/swagger.yaml
- scenarios/scenario-15/swagger.yaml
- scenarios/scenario-16/pets_swagger.yaml
- scenarios/scenario-16/stores_swagger.yaml
- scenarios/scenario-17/swagger.yaml
- scenarios/scenario-6/swagger.yaml
- Update operator docker image
- Update swagger basepath value with {version} template
> Update swagger basepath value with {version} template

- README.md
> Fixing readme file location

- apim-operator/deploy/controller-configs/controller_conf.yaml
- apim-operator/pkg/controller/api/api_controller.go
- apim-operator/pkg/controller/api/constants.go
- apim-operator/pkg/controller/targetendpoint/constants.go
- apim-operator/pkg/controller/targetendpoint/targetendpoint_controller.go
- scenarios/scenario-13/S01-APIM_for_Istio_Services/microservices.yaml
- scenarios/scenario-13/S01-APIM_for_Istio_Services/swagger.yaml
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/gateway-virtualservice.yaml
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/microservices.yaml
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/microservices.yaml
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/swagger.yaml
- scenarios/scenario-9/target-ep-rev.yaml
> Added port names for services and deployments

- api-operator/pkg/controller/api/api_controller.go
Swagger 2 was not unmarshalling properly due to a minor issue in the code. This PR fixes that issue.
> Link(s) to product …
> Fixing swagger2 support issue.

- api-operator/deploy/apim-analytics-configs/apim_analytics_conf.yaml
- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/controller/api/constants.go
- api-operator/pkg/controller/targetendpoint/constants.go
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/README.md
> Fixing scenarios for Istio

- api-operator/pkg/controller/api/api_controller.go
- scenarios/scenario-15/README.md
fix wso2/k8s-api-operator#274
- Update the created configmap `swaggerConfMap` instead of configmap got from k8s cluster.
```go
r.client.Update(context.TODO(), swaggerConfMap)
```
- Fix logging wrong err object.
> Fix update api issue

- README.md
- docs/GettingStarted/quick-start-guide.md
- scenarios/scenario-11/README.md
> Fixing localhost usage

- api-operator/deploy/crds/wso2_v1alpha1_targetendpoint_crd.yaml
- api-operator/pkg/apis/wso2/v1alpha1/targetendpoint_types.go
- api-operator/pkg/apis/wso2/v1alpha1/zz_generated.openapi.go
- Remove "serverless" field in "targetendpoint" CRD
- Mark optional in "targetendpoint" CRD: #226
> Remove "serverless" field in "targetendpoint" CRD

- docs/HowToGuide/working-with-aws.md
- scenarios/scenario-10/README.md
- scenarios/scenario-10/interceptor_swagger.yaml
- scenarios/scenario-8/README.md
- scenarios/scenario-9/README.md
- Updated docs in scenarios 8, 9, 10
- Update scenario 10 swagger's version to 'v1'
> Updated docs in scenarios 8, 9, 10

- scenarios/scenario-17/swagger.yaml
- scenarios/scenario-18/README.md
- scenarios/scenario-18/hello-world-service.yaml
- scenarios/scenario-18/swagger.yaml
> Add route scenario

- scenarios/scenario-7/products-privatejet.yaml
> Changing docker image name for scenario-7

- api-operator/deploy/controller-configs/controller_conf.yaml
- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/controller/targetendpoint/targetendpoint_controller.go
- scenarios/scenario-14/README.md
- scenarios/scenario-15/README.md
If the resource level endpoints are in another namespace, they would not get resolved. This PR fixed that issue for serverless, and regular endpoints at the resource level.
> Brief description of the new feature or …
> Fixing resource level service name resolution.

- api-operator/pkg/controller/api/api_controller.go
> Fix issue in route HTTP port

- README.md
- api-operator/deploy/controller-artifacts/operator.yaml
- api-operator/go.mod
- api-operator/go.sum
- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/controller/api/constants.go
- scenarios/scenario-14/swagger.yaml
- scenarios/scenario-17/README.md
- scenarios/scenario-17/swagger.yaml
> Fixing for ingresses

- api-operator/deploy/controller-configs/controller_conf.yaml
- toolkit-docker-image/Dockerfile
- Update docker images with 3.1.0
- Tested with Scenario 3
> Mgw 3.1.0 docker update

- api-operator/pkg/controller/api/api_controller.go
> Delete completed kaniko job

- api-operator/deploy/controller-artifacts/operator.yaml
- api-operator/deploy/controller-configs/controller_conf.yaml
- scenarios/scenario-14/README.md
- scenarios/scenario-16/README.md
> Release ready fixes

- scenarios/scenario-14/README.md
> fix README in scenario 14 

- api-operator/pkg/controller/api/api_controller.go
- This is due to the issue: https://github.com/wso2/k8s-api-operator/issues/295
- Should redone after fixing the above issue.
> Revert deleting kaniko job

- README.md
- distribution/pom.xml
- docs/GettingStarted/overview.md
- docs/GettingStarted/quick-start-guide.md
- operatorhub-resources/api-operator/1.1.0/api-operator.v1.1.0.clusterserviceversion.yaml
- operatorhub-resources/default-install/README.md
- operatorhub-resources/local-testing/README.md
- pom.xml
- scenarios/scenario-13/S01-APIM_for_Istio_Services/README.md
- scenarios/scenario-13/S01-APIM_for_Istio_Services/swagger.yaml
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/README.md
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/README.md
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/gateway-virtualservice.yaml
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/swagger.yaml
- scenarios/scenario-14/README.md
- scenarios/scenario-14/hello-world-serverless.yaml
- scenarios/scenario-14/swagger.yaml
- scenarios/scenario-15/README.md
- scenarios/scenario-16/README.md
- scenarios/scenario-18/README.md
- scenarios/scenario-7/README.md
- scenarios/scenario-8/README.md
- scenarios/scenario-9/README.md
> Updating the scenarios readme files

- docs/GettingStarted/overview.md
- docs/Troubleshooting/troubleshooting.md
- Update troubleshooting docs
- Replace kubectl with apictl
> Troubleshooting docs update

- docs/HowToGuide/WorkingWithDockerRegistries/reconfigure-registry.md
- docs/HowToGuide/configure-apictl-tool.md
- docs/HowToGuide/install-api-operator-in-cicd.md
- docs/Readme.md
- Add ci/cd api-operator installation docs
- Add reconfigure registry docs
> Add CI/CD api-operator installation docs

- api-operator/pkg/controller/ratelimiting/ratelimiting_controller.go
> Fix rate limiting duplication issue

- README.md
- api-operator/deploy/controller-artifacts/operator.yaml
- docs/GettingStarted/quick-start-guide.md
- scenarios/scenario-1/README.md
- scenarios/scenario-10/README.md
- scenarios/scenario-13/S01-APIM_for_Istio_Services/README.md
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/README.md
- scenarios/scenario-17/README.md
- scenarios/scenario-2/README.md
- scenarios/scenario-3/README.md
- scenarios/scenario-4/README.md
- scenarios/scenario-5/README.md
- scenarios/scenario-6/README.md
> Fixing formatting issues in samples

- README.md
- docs/GettingStarted/quick-start-guide.md
- docs/HowToGuide/configure-apictl-tool.md
- operatorhub-resources/api-operator/1.1.0/api-operator.v1.1.0.clusterserviceversion.yaml
- operatorhub-resources/default-install/README.md
- operatorhub-resources/namespace-install/README.md
- scenarios/scenario-13/S01-APIM_for_Istio_Services/README.md
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/README.md
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/README.md
> Updating the controller download location

- README.md
- docs/GettingStarted/quick-start-guide.md
- operatorhub-resources/api-operator/1.1.0/api-operator.v1.1.0.clusterserviceversion.yaml
- scenarios/scenario-16/README.md
- Use placeholders for commands
> Use placeholders for commands

- README.md
> Updating the root readme

- README.md
> Fixing apictl urls

- operatorhub-resources/api-operator/1.1.0/api-operator.v1.1.0.clusterserviceversion.yaml
> Updating description in csv

- api-operator/pkg/controller/api/api_controller.go
fix wso2/k8s-api-operator#336
- For more info refer the issue above
- WIll remove usage of `owner` object in functions in the refactoring PR. Example for interceptor handler `owner` object is not needed. No need to validate configmaps since it is done in this function.
> Set API owner reference to dependent configs

- operatorhub-resources/api-operator/1.1.0/api-operator.v1.1.0.clusterserviceversion.yaml
> Updating spec descriptors for operatorhub

- api-operator/pkg/controller/api/api_controller.go
> Fixing HPA issue.

- api-operator/pkg/kaniko/job.go
- api-operator/pkg/kaniko/volumes.go
- Set registry specific secrets to Kaniko job
> Set registry specific secrets to Kaniko job

- api-operator/deploy/crds/wso2_v1alpha1_api_crd.yaml
- api-operator/pkg/apis/wso2/v1alpha1/api_types.go
- api-operator/pkg/apis/wso2/v1alpha1/zz_generated.openapi.go
- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/controller/api/constants.go
- api-operator/pkg/mgw/api.go
> Improve apictl get api command

- api-operator/deploy/controller-artifacts/operator.yaml
- api-operator/deploy/controller-configs/controller_conf.yaml
- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/registry/registry.go
- Fix issue of not getting the image pull secret for checking existence of the MGW image.
- Do configuration changes only if the kaniko job is required to be created.
- Update kaniko version image - v0.24.0
- fix https://github.com/wso2/k8s-api-operator/issues/350
> Fix API docker image override issue in GCR registry

- README.md
- docs/GettingStarted/quick-start-guide.md
> [Docs] Update quick-start-guide

- api-operator/pkg/analytics/config.go
- api-operator/pkg/kaniko/volumes.go
- scenarios/scenario-1/README.md
- scenarios/scenario-13/S01-APIM_for_Istio_Services/microservices.yaml
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/microservices.yaml
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/microservices.yaml
- scenarios/scenario-14/README.md
- scenarios/scenario-14/hello-world-serverless.yaml
- scenarios/scenario-17/hello-world-service.yaml
- scenarios/scenario-19/README.md
- scenarios/scenario-2/README.md
- scenarios/scenario-3/README.md
- scenarios/scenario-4/README.md
- scenarios/scenario-7/products-privatejet.yaml
- scenarios/scenario-8/inventory-sidecar.yaml
- scenarios/scenario-9/target-ep-inv.yaml
- scenarios/scenario-9/target-ep-prod.yaml
- scenarios/scenario-9/target-ep-rev.yaml
This PR fixes some of the issues encountered while testing operator scenarios with 1.2.0-alpha.
- Updated TargetEndpoint CR in scenarios to support the new CRD.
- Fixed an issue where duplicate volumes were being created in the shared mode scenario.
- Fixed an issue where analytics secret was not created in user namespace.
Tested in Minikube v1.9.2 and GKE with kubernets versions 1.15+
> Fixing scenario related issues for 1.2.0-beta release

- api-operator/deploy/controller-configs/controller_conf.yaml
- api-operator/pkg/controller/api/api_controller.go
- Fix update API
- Add default ingress configs for CORS
> Fix update API and add default ingress configs for CORS

- api-operator/deploy/controller-configs/mgw_conf_mustache.yaml
Enable Http2 in mgw_conf_mustache.
> Enable http2 in mgw mustache

- scenarios/scenario-21/README.md
- scenarios/scenario-21/default-security.yaml
- Add a scenario (Scenario-21) including the documentation related to deploying an API using WSO2 API manager locally.
> Add scenario docs for Deploy an API using WSO2 API Manager locally

- scenarios/scenario-20/README.md
> Update scenario 20

- scenarios/scenario-17/README.md
> Update scenario 17 readme

- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/mgw/api.go
Updates the API details by adding the ingress IP address to the API Endpoint.
```
>> apictl get apis
NAME              INITIAL-REPLICAS   MODE         ENDPOINT                               AGE
hello-world-api   1                  privateJet   mgw.ingress.wso2.com, 35.247.135.234   5m
```
> Adding ingress ip to endpoint details

- api-operator/pkg/mgw/virtualservice.go
- scenarios/scenario-13/S01-APIM_for_Istio_Services/README.md
- scenarios/scenario-13/S01-APIM_for_Istio_Services/microservices.yaml
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/README.md
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/microservices.yaml
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/README.md
> Update Istio docs

- README.md
- api-operator/deploy/sample-definitions/wso2_v1alpha1_targetendpoint_cr.yaml
- docs/GettingStarted/overview.md
- docs/GettingStarted/quick-start-guide.md
- docs/HowToGuide/OverviewOfCrds/apply-rate-limiting-to-api.md
- docs/HowToGuide/OverviewOfCrds/apply-security-to-api.md
- docs/HowToGuide/OverviewOfCrds/perform-api-operations.md
- docs/HowToGuide/OverviewOfCrds/working-with-endpoints.md
- docs/HowToGuide/WorkingWithDockerRegistries/reconfigure-registry.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-aws.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-gcr.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-http-https-repository.md
- docs/HowToGuide/configurations-overview.md
- docs/HowToGuide/configure-apictl-tool.md
- docs/HowToGuide/enable-analytics-to-api.md
- docs/HowToGuide/install-api-operator-in-cicd.md
- docs/HowToGuide/working-with-deployment-modes.md
- docs/HowToGuide/working-with-kaniko-additional-flags.md
- docs/Troubleshooting/troubleshooting.md
- scenarios/scenario-13/S01-APIM_for_Istio_Services/README.md
- scenarios/scenario-13/S01-APIM_for_Istio_Services/microservices.yaml
- scenarios/scenario-14/README.md
- scenarios/scenario-14/hello-world-serverless.yaml
- scenarios/scenario-18/hello-world-service.yaml
- toolkit-docker-image/Dockerfile
> Update Doc Space

- operatorhub-resources/api-operator/1.2.0/api-operator.v1.2.0.clusterserviceversion.yaml
- operatorhub-resources/api-operator/1.2.0/wso2.com_apis_crd.yaml
- operatorhub-resources/api-operator/1.2.0/wso2.com_ratelimitings_crd.yaml
- operatorhub-resources/api-operator/1.2.0/wso2.com_securities_crd.yaml
- operatorhub-resources/api-operator/1.2.0/wso2.com_targetendpoints_crd.yaml
- operatorhub-resources/api-operator/api-operator.package.yaml
- operatorhub-resources/creating-new-version/README.md
- operatorhub-resources/default-install/README.md
- operatorhub-resources/local-testing/README.md
This PR updated the operatorhub resources to 1.2.0
> Updating operatorhub resources to 1.2.0

- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/endpoints/sidecar.go
- api-operator/pkg/swagger/endpoints.go
- docs/HowToGuide/OverviewOfCrds/working-with-endpoints.md
- scenarios/scenario-14/README.md
- scenarios/scenario-14/swagger.yaml
- scenarios/scenario-17/swagger.yaml
- scenarios/scenario-18/swagger.yaml
- scenarios/scenario-20/README.md
- scenarios/scenario-20/swagger.yaml
- scenarios/scenario-7/README.md
- scenarios/scenario-7/swagger.yaml
- scenarios/scenario-8/README.md
- scenarios/scenario-8/swagger.yaml
- scenarios/scenario-9/README.md
- scenarios/scenario-9/swagger.yaml
- fix https://github.com/wso2/k8s-api-operator/issues/424
- Refactor and fix issue of not supporting urls: []string as Target EP CR in endpoints.go
- API level
- Resource level
> Refactor endpoint.go and Fix issue of not supporting urls: []string as Target EP

- api-operator/deploy/controller-artifacts/role.yaml
> Update role for virtualservices

- scenarios/scenario-18/README.md
> Updating scenario 18 readme

- api-operator/deploy/controller-configs/controller_conf.yaml
> Updating MGW docker images to MGW 3.2.0-RC2
> Updating to MGW 3.2.0-RC2

- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/mgw/api.go
- api-operator/pkg/mgw/virtualservice.go
- api-operator/pkg/registry/utils/utils.go
- Update Logs with Request name in API Controller
- Requeue after 10 seconds if there is a configuration issue. No point of processing with invalid configs, user should first re-configure them.
**NOTE:** Return without the error, if error is returned then requeue will happen immediately.
```go
return reconcile.Result{RequeueAfter: 10 * time.Second}, nil
```
- Fix issue of getting image tags
> Update Logs with Request name in API Controller

- README.md
- scenarios/README.md
- scenarios/scenario-24/README.md
- scenarios/scenario-24/jwt-security-sub.yaml
- scenarios/scenario-24/swagger.yaml
- Adds Scenario docs for Connect to WSO2 API Manager as event hub to validate JWT subscriptions
> Add Scenario docs for Connect to WSO2 API Manager as event hub to validate JWT subscriptions

- scenarios/scenario-21/README.md
> Updating scenario 21

- README.md
- distribution/pom.xml
- k8s-artifacts/api-portal-with-analytics/api-analytics/analytics-dashboard-conf-configmap.yaml
- k8s-artifacts/api-portal-with-analytics/api-analytics/analytics-dashboard-deployment.yaml
- k8s-artifacts/api-portal-with-analytics/api-analytics/analytics-worker-deployment.yaml
- k8s-artifacts/api-portal-with-analytics/api-portal/wso2apim-configmap.yaml
- k8s-artifacts/api-portal-with-analytics/api-portal/wso2apim-deployment.yaml
- k8s-artifacts/api-portal/wso2apim-configmap.yaml
- k8s-artifacts/api-portal/wso2apim-deployment.yaml
- k8s-artifacts/wso2am-operator/api-portal/2-wso2apim-configmap.yaml
- scenarios/scenario-13/S01-APIM_for_Istio_Services/README.md
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/README.md
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/README.md
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/swagger.yaml
- scenarios/scenario-14/README.md
- scenarios/scenario-20/README.md
- scenarios/scenario-23/README.md
- scenarios/scenario-24/README.md
> This PR will upgrade the  artifacts to APIM 3.2.0 and update the readme files to api-operator 1.2.0
> Upgrading artifacts to APIM 3.2.0 and updating readme files

- operatorhub-resources/api-operator/1.2.0/api-operator.v1.2.0.clusterserviceversion.yaml
- Update 1.2.0 Operator Hub CSV with maintainers' emails
- https://github.com/operator-framework/community-operators/pull/2306
- https://github.com/operator-framework/community-operators/pull/2307
> Update 1.2.0 Operator Hub CSV

- README.md
- api-operator/README.md
- api-operator/deploy/controller-artifacts/operator.yaml
- distribution/pom.xml
- docs/GettingStarted/quick-start-guide.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-aws.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-gcr.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-http-https-repository.md
- docs/HowToGuide/install-api-operator-in-cicd.md
- operatorhub-resources/creating-new-version/README.md
- operatorhub-resources/default-install/README.md
- operatorhub-resources/local-testing/README.md
- operatorhub-resources/namespace-install/README.md
- pom.xml
- scenarios/scenario-13/S01-APIM_for_Istio_Services/README.md
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/README.md
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/README.md
- scenarios/scenario-22/README.md
- scenarios/scenario-24/README.md
- Update API Operator version as 1.2.1
> Update API Operator version as 1.2.1

- operatorhub-resources/api-operator/1.2.1/api-operator.v1.2.1.clusterserviceversion.yaml
- operatorhub-resources/api-operator/1.2.1/wso2.com_apis_crd.yaml
- operatorhub-resources/api-operator/1.2.1/wso2.com_ratelimitings_crd.yaml
- operatorhub-resources/api-operator/1.2.1/wso2.com_securities_crd.yaml
- operatorhub-resources/api-operator/1.2.1/wso2.com_targetendpoints_crd.yaml
- operatorhub-resources/api-operator/api-operator.package.yaml
Add Operator Hub resources for operator version 1.2.1
- Verified with operator-courier
- Tested with Market Place operator by pushing the bundle to quay.io
> Add Operator Hub resources for operator version 1.2.1

- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/swagger/swagger.go
Fixes https://github.com/wso2/k8s-api-operator/issues/441
Fixes https://github.com/wso2/k8s-api-operator/issues/464
> Check if API is deleted when waiting for service endpoint

- api-operator/pkg/endpoints/sidecar.go
This PR adds the resource requests and limits for the containers in sidecar mode.
Fixes https://github.com/wso2/k8s-api-operator/issues/462
> Add resource requirements in sidecar mode

- docs/HowToGuide/WorkingWithDockerRegistries/working-with-acr.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-aws.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-http-https-repository.md
- docs/HowToGuide/install-api-operator-in-cicd.md
- docs/Readme.md
Add docs for issue: wso2/k8s-api-operator#434
> Add docs for configuring Azure Container Registries

- README.md
- api-operator/README.md
- api-operator/deploy/controller-artifacts/operator.yaml
- api-operator/deploy/controller-configs/controller_conf.yaml
- api-operator/pkg/controller/api/api_controller.go
- distribution/pom.xml
- docs/GettingStarted/quick-start-guide.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-acr.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-aws.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-gcr.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-http-https-repository.md
- docs/HowToGuide/install-api-operator-in-cicd.md
- operatorhub-resources/creating-new-version/README.md
- operatorhub-resources/default-install/README.md
- operatorhub-resources/local-testing/README.md
- operatorhub-resources/namespace-install/README.md
- pom.xml
- scenarios/scenario-13/S01-APIM_for_Istio_Services/README.md
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/README.md
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/README.md
- scenarios/scenario-22/README.md
This PR,
- fixes a minor issue with jwt configs
- updates the operator version for the release.
> Update Operator version to 1.2.2

- operatorhub-resources/api-operator/1.2.2/api-operator.v1.2.2.clusterserviceversion.yaml
- operatorhub-resources/api-operator/1.2.2/wso2.com_apis_crd.yaml
- operatorhub-resources/api-operator/1.2.2/wso2.com_ratelimitings_crd.yaml
- operatorhub-resources/api-operator/1.2.2/wso2.com_securities_crd.yaml
- operatorhub-resources/api-operator/1.2.2/wso2.com_targetendpoints_crd.yaml
- operatorhub-resources/api-operator/api-operator.package.yaml
- operatorhub-resources/local-testing/README.md
- operatorhub-resources/local-testing/olm.sh
This PR updates the Operatorhub related resources for 1.2.2 release.
> Update Operatorhub resources for 1.2.2

- .github/workflows/go.yml
- api-operator/cmd/manager/main.go
- api-operator/pkg/controller/targetendpoint/targetendpoint_controller.go
- api-operator/pkg/maps/utils.go
- api-operator/pkg/maps/utils_test.go
- api-operator/run-tests.sh
- Add GitHub workflow to go vet, build and test operator
- Removed go vet warnings in TargetEp controller
- Added a sample unit test
> Add GitHub workflow to go vet, build and test operator

- LICENSE.txt
Needs to show licenses of third part libraries used
- Checked third party libraries from go.mod
- Get all licenses of third party libraries from vendors directory
> Added licenses of third party libraries (#513)

- api-operator/deploy/controller-artifacts/operator.yaml
Correct docker image of API Operator
> Update docker image version

- docs/HowToGuide/working-with-deployment-modes.md
This fixes issues raised in https://github.com/wso2/k8s-api-operator/pull/389#discussion_r553816008
> Fixing formatting issues

- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/controller/ratelimiting/ratelimiting_controller.go
- api-operator/pkg/controller/security/security_controller.go
- api-operator/pkg/controller/targetendpoint/targetendpoint_controller.go
No need to add separate pod watches
Remove all unwanted(additional) pod watches.
#533
> Removed pod watches (master branch)

- scenarios/scenario-5/README.md
See #543 
Needs to remove the unsupported command.
#543
> Removed setting oauth2 access token

- api-operator/README.md
README.md needs to be updated on sdk version for generating crds.
> Added sdk version for crd creation

- api-operator/README.md
- distribution/pom.xml
- pom.xml
Adding docker image build support 
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …
> Adding image build support with mvn

- README.md
- api-operator/README.md
- api-operator/deploy/controller-artifacts/operator.yaml
- distribution/pom.xml
- pom.xml
> Upgrade version to 2.0.0-alpha

- .github/workflows/go.yml
Upload test coverage reports to Codecov
> Upload test coverage reports to Codecov

- api-operator/deploy/controller-configs/integration_controller_conf.yaml
Fixes: https://github.com/wso2/micro-integrator/issues/2133
> Fix [MI-2133] Fix Ingress properties in integration_controller_conf.yaml

- api-operator/deploy/controller-configs/integration_controller_conf.yaml
> Change default HPA target cpu utilization 

- operatorhub-resources/api-operator/2.0.0/api-operator.v2.0.0.clusterserviceversion.yaml
Update the link to install default configs
fix https://github.com/wso2/k8s-api-operator/issues/587
> Update Operator-hub description to install configs

- api-operator/pkg/analytics/config.go
- api-operator/pkg/controller/api/api_controller.go
- api-operator/pkg/mgw/config.go
- api-operator/pkg/mgw/deployment.go
- api-operator/pkg/mgw/ingress.go
- api-operator/pkg/mgw/route.go
- api-operator/pkg/mgw/service.go
- api-operator/pkg/mgw/virtualservice.go
- api-operator/pkg/security/credentials.go
- api-operator/pkg/security/security.go
> Refactor Remove global var for MG Configuration

- README.md
- api-operator/deploy/controller-artifacts/operator.yaml
- api-operator/deploy/controller-configs/controller_conf.yaml
- api-operator/deploy/kustomization.yaml
- distribution/assembly.xml
- distribution/pom.xml
- docs/GettingStarted/quick-start-guide.md
- docs/HowToGuide/production-deployment-guide.md
- operatorhub-resources/creating-new-version/README.md
- operatorhub-resources/default-install/README.md
- operatorhub-resources/local-testing/README.md
- operatorhub-resources/namespace-install/README.md
- pom.xml
- scenarios/scenario-13/S01-APIM_for_Istio_Services/README.md
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/README.md
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/README.md
- scenarios/scenario-22/README.md
- scenarios/scenario-23/README.md
> API Operator 1.2.3 Release Changes

- README.md
- api-operator/README.md
- docs/GettingStarted/quick-start-guide.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-acr.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-aws.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-gcr.md
- docs/HowToGuide/WorkingWithDockerRegistries/working-with-http-https-repository.md
- docs/HowToGuide/install-api-operator-in-cicd.md
- docs/HowToGuide/production-deployment-guide.md
- operatorhub-resources/local-testing/README.md
- operatorhub-resources/namespace-install/README.md
- scenarios/scenario-13/S01-APIM_for_Istio_Services/README.md
- scenarios/scenario-13/S02-APIM_for_Istio_Services_MTLS/README.md
- scenarios/scenario-13/S03-API_Gateway_In_Istio_As_A_Service/README.md
> Upgrade operator version as 1.2.3

- operatorhub-resources/api-operator/1.2.3/api-operator.v1.2.3.clusterserviceversion.yaml
- operatorhub-resources/api-operator/1.2.3/wso2.com_apis_crd.yaml
- operatorhub-resources/api-operator/1.2.3/wso2.com_ratelimitings_crd.yaml
- operatorhub-resources/api-operator/1.2.3/wso2.com_securities_crd.yaml
- operatorhub-resources/api-operator/1.2.3/wso2.com_targetendpoints_crd.yaml
- operatorhub-resources/api-operator/2.0.0/api-operator.v2.0.0.clusterserviceversion.yaml
- operatorhub-resources/api-operator/api-operator.package.yaml
fix https://github.com/wso2/k8s-api-operator/issues/603
> OperatorHub Resources for API Operator v1.2.3

- README.md
- api-operator/README.md
- api-operator/deploy/controller-artifacts/operator.yaml
- distribution/pom.xml
- pom.xml
Upgrade version from 2.0.0 to 2.0.1
- https://github.com/wso2/k8s-api-operator/pull/608
> Version upgrade to 2.0.1

- README.md
- api-operator/README.md
- api-operator/deploy/controller-artifacts/operator.yaml
- distribution/pom.xml
- pom.xml
> Prepare for 2.0.2 release
